default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['DATABASE_HOST'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  pool: 5
  port: <%= ENV['DATABASE_PORT'] || 5432 %>

development:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] || 'db-1' %>

test:
  <<: *default
  database: shop_test

production:
  <<: *default
  # Rails приоритетно смотрит на url, если он задан
  url: <%= ENV['DATABASE_URL'] %> 
  database: shop_production # Это будет проигнорировано, если в URL уже есть имя базы
